name: Electron Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write


jobs:

  build:

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest


    runs-on: ${{ matrix.os }}


    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Install dependencies
        run: npm install


      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install


      - name: Build frontend
        run: |
          cd frontend
          npm run build


      - name: Build Electron
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build


      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-${{ matrix.os }}
          path: release/*



  release:

    needs: build

    runs-on: ubuntu-latest


    steps:

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release


      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/**/*.AppImage
            release/**/*.exe
            release/**/*.dmg
            release/**/*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}