name: Electron Release

on:
  push:
    tags:
      - "v*"


jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Install root dependencies
        run: npm install


      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install


      - name: Build frontend
        run: |
          cd frontend
          npm run build


      - name: Build Electron
        run: npm run build